import assert from 'node:assert/strict'
import { build } from 'esbuild'
import { createRequire } from 'node:module'
import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { readFileSync } from 'node:fs'
import { candidate, fixtureResearch as research, fixtureDashboard as dashboard } from './system-activity-fixtures.mjs'

const result = await build({ entryPoints: ['src/SystemActivity.tsx','src/systemActivityModel.ts','src/SystemNetwork.tsx'], bundle: true, write: false,
  outdir: 'unused', loader: {'.png':'file'}, platform: 'node', format: 'cjs', jsx: 'automatic', external: ['react','react/jsx-runtime'],
  plugins: [{ name: 'isolated-render', setup(b) {
    b.onResolve({ filter: /^\.\/appShared$/ }, () => ({ path: 'stub', namespace: 'stub' }))
    b.onResolve({ filter: /\.css$/ }, () => ({ path: 'css', namespace: 'stub' }))
    b.onLoad({ filter: /.*/, namespace: 'stub' }, () => ({ contents: "export const API_ORIGIN='http://isolated.invalid'; export const useLanguage=()=>({language:'he',setLanguage:()=>{}}); export const useTheme=()=>({theme:'dark',setTheme:()=>{}})" }))
  } }] })
const load = name => {
  const m = { exports: {} }
  new Function('require','module','exports',result.outputFiles.find(f => f.path.endsWith(name+'.js')).text)(createRequire(import.meta.url), m, m.exports)
  return m.exports
}
const { buildActivity, activityRevision, detectActivityUpdates, finite, STATE_SYMBOLS, STATIONS } = load('systemActivityModel')
const { SystemActivityView, StockFocus, StationFlow, activityLevels } = load('SystemActivity')
const { buildNetwork, buildConstellation, COMPACT_CLUSTERS, buildEvidenceSweep, networkControls, networkMotionAllowed, NETWORK_LIMIT, SystemNetwork } = load('SystemNetwork')
let assertions = 0
const check = v => { assert.ok(v); assertions++ }
const equal = (a,b) => { assert.deepEqual(a,b); assertions++ }
const items = buildActivity(research,dashboard)
equal(items.length,9)
const stock = ticker => items.find(v => v.ticker === ticker)
equal(stock('ALFA').station,'technical')
equal(stock('BETA').station,'targets') // PASS is not proof of evidence or AI
equal(stock('GAMA').station,'evidence')
equal(stock('DELT').station,'ai')
equal(stock('ECHO').state,'blocked')
equal(stock('ECHO').reason,'allocation_blocked')
equal(stock('FOXT').station,'order')
equal(stock('FOXT').state,'waiting')
equal(stock('GOLF').state,'uncertain')
equal(stock('HOTL').station,'position')
equal(stock('INDI').station,'exit')
equal(items.filter(i => i.ticker === 'HOTL').length,1) // Shadow not an independent main entry
equal(new Set(items.map(i => i.id)).size,items.length)
equal(buildActivity(null,null),[])
equal(buildActivity(research,{signals:[],trades:[{id:100,ticker:'OLD',status:'closed',closed_at:'2026-10-01T15:00:00Z'}]}).filter(i => i.ticker==='OLD').length,0)
equal(buildActivity(research,{signals:[],trades:[{id:100,ticker:'OLD',status:'open',opened_at:'2026-10-01T15:00:00Z'}]}).filter(i => i.ticker==='OLD').length,1)
equal(buildActivity(research,null).filter(i => i.kind === 'signal').length,5) // research link not lost if dashboard is capped
const unlinked = buildActivity(null,{ signals: [{id:9,ticker:'TEST',actual_entry:100,status:'ENTERED'}] })[0]
equal(unlinked.state,'uncertain'); check(unlinked.station !== 'position')
const expired = buildActivity(null,{ signals: [{id:9,ticker:'TEST',status:'EXPIRED'}] })[0]
equal(expired.station,'signal'); equal(expired.reason,'EXPIRED')
const older = candidate('ALFA',{scan_id:'older',at:'2026-10-08T15:00:00Z',rejection:'pre_no_fresh_quote'})
equal(buildActivity({...research,records:[older,...research.records]},dashboard).filter(i => i.ticker === 'ALFA').length,1)
equal(buildActivity({...research,records:[older,...research.records]},dashboard).find(i => i.ticker === 'ALFA').reason,null)
equal(buildActivity({records:[candidate('WAIT',{rejection:'pre_waiting_regular_session',rejection_stage:'session_wait'})]},null)[0].state,'waiting')
equal(finite(null),null); equal(finite(''),null); equal(finite(false),null); equal(finite(Infinity),null); equal(finite(0),0)
equal(activityRevision(stock('HOTL')),activityRevision(buildActivity({...research,generated_at:'2030-01-01T00:00:00Z'},dashboard).find(i => i.ticker==='HOTL')))
check(activityRevision(stock('GOLF')) !== activityRevision({...stock('GOLF'),state:'waiting'}))
const render = props => renderToStaticMarkup(createElement(SystemActivityView,{he:true,research,dashboard,...props}))
const html = render({selected:'trade:40'})
check(html.includes('מה קורה במערכת?') && !html.includes('תחנות ומניות'))
check(html.includes('aria-expanded="true"') && html.includes('station-records-position'))
check(html.includes('dir="rtl"') && html.includes('<bdi>HOTL</bdi>'))
check(html.includes('יתרה מהפוזיציה') && html.includes('100.00%'))
check(html.includes('ממומש נטו') && html.includes('חלק פתוח ברוטו'))
check(html.includes('אינן תשואת תיק') && html.includes('Shadow אינו תיק עצמאי'))
check(!html.includes('$') && !html.includes('NaN') && !html.includes('Infinity'))
check(!html.includes('system-evidence-spider') && !render({he:false}).includes('Idle movement'))
check(html.includes('106.00') && !html.includes('TP2: 106.00'))
check(html.includes('המדגם מוגבל'))
check(render({selected:'signal:1'}).includes('סיגנל כשיר; הקצאת הדמה חסומה'))
check(render({selected:'signal:3'}).includes('אי־ודאות בהתאוששות'))
check(render({selected:'scan:synthetic-ALFA:ALFA'}).includes('אין סיגנל מקושר במדגם'))
const singleV1 = {...dashboard,signals:[{id:8,ticker:'VONE',planned_entry:100,current_stop:97,rr1:1,rr2:2,rr3:3,tp1:103,tp2:106,tp3:109,operational_tp1_pct:0,operational_tp2_pct:1,operational_tp3_pct:0,status:'ACTIVE'}],trades:[]}
const v1 = render({dashboard:singleV1,research:{records:[]},selected:'signal:8'})
check(v1.includes('2.00R') && !v1.includes('1.00R'))
check(v1.includes('106.00'))
const escape = render({dashboard:{...dashboard,signals:dashboard.signals.map(s => ({...s,company:'<img src=x onerror=alert(1)>'}))}})
check(escape.includes('&lt;img') && !escape.includes('<img src=x'))
check(render({error:'HTTP 503'}).includes('role="alert"'))
check(render({research:null,dashboard:null}).includes('ממתין לנתונים'))
check(render({dashboard:{...dashboard,market:{is_open:false}}}).includes('מחוץ למסחר'))
check(render({he:false}).includes('System in motion'))
check(render({onlyFollowed:true,followed:['HOTL']}).includes('HOTL'))
check(render({onlyFollowed:true,followed:['HOTL']}).includes('<bdi>ALFA</bdi>')) // obsolete browser preferences cannot filter the public surface
for(const he of [true,false]) {
  const publicView=render({he})
  check(!publicView.includes('system-follow')&&!publicView.includes('type="checkbox"'))
  check(publicView.includes(he?'התצוגה הציבורית היא לצפייה בלבד':'This public view is read-only'))
}
check(render({station:'order'}).includes('<bdi>FOXT</bdi>'))
check(!render({station:'order'}).includes('<bdi>DELT</bdi>'))
check(render({selected:'disappeared'}).includes('אין בכך הוכחה שהפוזיציה נסגרה'))
const legacy = {...dashboard,trades:[{...dashboard.trades[0],legacy_position_id:7}]}
check(render({dashboard:legacy,selected:'trade:40',research:{...research,outcomes:[{trade_id:40,cohort:'Legacy',realized_net_pct:null,realized_net_r:null}]}}).includes('חסרה היסטוריה מלאה'))
const css = readFileSync('src/systemActivity.css','utf8')
check(css.includes('prefers-reduced-motion:reduce'))
check(!css.includes('system-visual-tour'))
check(!css.includes('system-evidence-spider'))
check(!css.includes('system-crawler'))
check(!css.includes('system-evidence-sweep'))
check(!css.includes('system-spider-step'))
const graph = buildNetwork(items)
equal(graph.flatMap(c => c.nodes).length, items.length)
equal(graph.flatMap(c => c.nodes.map(n => n.item.id)).sort(), items.map(i => i.id).sort())
equal(buildNetwork([...items].reverse()), graph)
const dense = Array.from({length: 100}, (_, n) => ({...stock('HOTL'), id:`synthetic:${n}`}))
const denseCluster = buildNetwork(dense).find(c => c.station === 'position')
equal(denseCluster.nodes.length, NETWORK_LIMIT)
equal(buildNetwork(dense,true).find(c=>c.station==='position').nodes.length,4)
equal(buildNetwork(dense,true).find(c=>c.station==='position').omitted,96)
equal(denseCluster.omitted, 100-NETWORK_LIMIT)
check(denseCluster.nodes.every(n => Number.isFinite(n.x) && Number.isFinite(n.y)))
equal(buildNetwork([]).flatMap(c => c.nodes), [])
const compactGraph = buildNetwork(items,true)
equal(compactGraph.flatMap(c=>c.nodes.map(n=>n.item.id)).sort(),items.map(i=>i.id).sort())
equal(buildNetwork([...items].reverse(),true),compactGraph)
check(compactGraph.flatMap(c=>c.nodes).every(n=>n.x>=0 && n.x<=380 && n.y>=0 && n.y<=776))
equal(COMPACT_CLUSTERS.technical.x,94); equal(COMPACT_CLUSTERS.targets.x,286)
equal(COMPACT_CLUSTERS.exit.y,640)
for (const compact of [false,true]) {
  const field = buildConstellation(compact)
  equal(field,buildConstellation(compact))
  equal(field.flatMap(c=>c.points).length,compact?320:640)
  check(field.every(c=>c.edges.length<=c.points.length*3))
  check(field.flatMap(c=>c.points).every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)))
  check(field.flatMap(c=>c.points).every(p=>p.x>=0 && p.x<=(compact?380:1200) && p.y>=0 && p.y<=(compact?776:800)))
  check(field.every(c=>c.edges.every(e=>c.points.includes(e.a)&&c.points.includes(e.b))))
}
equal(buildEvidenceSweep(items,[]).path,'M 610 340')
const now = Date.parse('2026-10-09T15:10:00Z'), baseline = now-60000
const freshAlfa = {...stock('ALFA'),at:'2026-10-09T15:09:40Z',station:'targets',reason:'pre_no_forward_zone'}
const updatedItems = items.map(i => i.id===freshAlfa.id ? freshAlfa : i)
equal(detectActivityUpdates(null,updatedItems,baseline,now),[])
equal(detectActivityUpdates(items,items,baseline,now),[])
equal(detectActivityUpdates(items,[{...freshAlfa,at:stock('ALFA').at}],baseline,now),[])
equal(detectActivityUpdates(items,[{...freshAlfa,at:'2026-10-09T15:11:00Z'}],baseline,now),[])
equal(detectActivityUpdates(items,[{...freshAlfa,at:'2026-10-09T15:05:00Z'}],baseline,now),[])
equal(detectActivityUpdates(items,[{...freshAlfa,at:null}],baseline,now),[])
const observed = detectActivityUpdates(items,updatedItems,baseline,now)
equal(observed.length,1); equal(observed[0].item.id,freshAlfa.id)
equal(detectActivityUpdates(updatedItems,updatedItems,now,now+1000),[])
equal(detectActivityUpdates(items,[{...freshAlfa,id:'new-history',at:'2026-10-09T15:08:50Z'}],baseline,now),[])
equal(detectActivityUpdates(items,[{...freshAlfa,id:'new-event'}],baseline,now).length,1)
const evidenceSweep = buildEvidenceSweep(updatedItems,observed)
equal(evidenceSweep.shown.length,1)
equal(evidenceSweep.end.x,buildNetwork(updatedItems).find(c=>c.station==='targets').nodes.find(n=>n.item.id===freshAlfa.id).x)
const compactSweep = buildEvidenceSweep(updatedItems,observed,{x:190,y:336},true)
equal(compactSweep.end.x,buildNetwork(updatedItems,true).find(c=>c.station==='targets').nodes.find(n=>n.item.id===freshAlfa.id).x)
check(compactSweep.path.startsWith('M 190 336'))
check(!evidenceSweep.path.includes('1040 370')) // no invented visit to AI
equal(buildEvidenceSweep(items,observed).shown,[]) // no old-stage update rendered in a different current station
equal(buildEvidenceSweep([],observed).shown,[])
equal(buildEvidenceSweep(updatedItems,observed,{x:12,y:34}).path.split(' L ')[0],'M 12 34')
const many = items.map(i=>({key:i.id,item:i}))
equal(buildEvidenceSweep(items,many).shown.length,4)
equal(buildEvidenceSweep(items,many).omitted,5)
const network = props => renderToStaticMarkup(createElement(SystemNetwork,{he:true,items,changed:new Set(),station:'all',setStation:()=>{},selected:null,select:()=>{},available:true,marketOpen:true,...props}))
check(!network({}).includes('evidence-motion-enabled'))
check(!network({available:false}).includes('evidence-motion-enabled'))
check(!network({items:[]}).includes('evidence-motion-enabled'))
check(network({}).includes('סימון מניה: שינוי מתועד שנקלט — לא מצב Worker בזמן אמת'))
check(!network({}).includes('system-evidence-spider') && !network({}).includes('<animateMotion'))
check(network({}).includes('ממתין לשינוי מתועד חדש'))
check(!network({}).includes('השהה תנועה'))
check(!network({available:false}).includes('system-evidence-spider'))
check(network({}).includes('נקודות הרקע דקורטיביות'))
check(!network({}).includes('התקרבות') && !network({}).includes('תצוגת 3D') && network({}).includes('איך לקרוא את הרשת'))
check(network({items:[]}).includes('00 רשומות במדגם'))
equal((network({}).match(/class="system-graph-stock /g)||[]).length,items.length)
equal((network({items:[]}).match(/class="system-graph-stock /g)||[]).length,0)
check(network({}).includes('מסלול מניה: HOTL'))
check(network({changed:new Set(['trade:40'])}).includes('system-arrival'))
check(!network({available:false,changed:new Set(['trade:40'])}).includes('system-arrival'))
const networkSource = readFileSync('src/SystemNetwork.tsx','utf8')
// Narrow phones and desktop sidebars must not scale the controls below their
// screen-space type/touch sizes. The SVG viewBox never depends on selection.
for (const [compact,width] of [[true,288],[true,358],[true,398],[true,800],[false,826],[false,882],[false,1042],[false,1342]]) {
  const ui=networkControls(compact,width),scale=width/(compact?380:1200)
  check(Math.abs(ui.buttonHeight*scale-48)<1e-8)
  check(Math.abs(ui.fontSize*scale-14)<1e-8)
  check(Math.abs(ui.labelFontSize*scale-13)<1e-8)
  check(ui.buttonWidth*scale<width)
  const graph=buildNetwork(Array.from({length:64},(_,n)=>({...items[0],id:`crowded:${n}`,station:STATIONS[Math.floor(n/8)]})),compact)
  const headers=graph.map(c=>({left:c.x-ui.buttonWidth/2,right:c.x+ui.buttonWidth/2,top:c.y-ui.buttonOffset,bottom:c.y-ui.buttonOffset+ui.buttonHeight}))
  const labels=graph.flatMap(c=>c.nodes.map(n=>({left:n.x-40,right:n.x+40,top:n.y+9,bottom:n.y+9+ui.labelHeight})))
  const overlaps=(a,b)=>a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top
  check(headers.every(h=>h.top>=0&&h.left>=0&&h.right<=(compact?380:1200)))
  check(labels.every(l=>l.bottom<=(compact?776:800)))
  check(!headers.some(h=>labels.some(l=>overlaps(h,l))))
  check(!labels.some((l,n)=>labels.slice(n+1).some(other=>overlaps(l,other))))
  if(compact) {
    const rows=buildNetwork(Array.from({length:32},(_,n)=>({...items[0],id:`readable:${n}`,station:STATIONS[Math.floor(n/4)]})),true)
    for(let row=0;row<3;row++) {
      const previous=rows[row*2],next=rows[(row+1)*2]
      const labelBottom=Math.max(...previous.nodes.map(n=>n.y+9))+ui.labelHeight
      check(next.y-ui.buttonOffset-labelBottom>=6/scale)
    }
  }
}
for(const invalidWidth of [0,NaN,Infinity,-1]) check(Number.isFinite(networkControls(true,invalidWidth).fontSize))
check(networkSource.includes('observer.disconnect()')&&networkSource.includes('new ResizeObserver(update)'))
check(networkSource.includes('n.item.ticker}</div>')) // no silent ticker truncation in source
check(css.includes('text-overflow: ellipsis')&&css.includes('height: 100%; gap: calc(8px * var(--map-control-unit,1))'))
check(!networkSource.includes('fetch(') && !networkSource.includes('Math.random'))
check(networkSource.includes('[compact,selected]')) // no pan or zoom on selection
check(!networkSource.includes('Web3D')&&!networkSource.includes('setZoom')&&!networkSource.includes('onPointerMove'))
check(!networkSource.includes('EvidenceSpider')&&!networkSource.includes('spiderTexture'))
for (const requested of [false,true]) for (const reduced of [false,true]) for (const explicitlyEnabled of [false,true]) {
  equal(networkMotionAllowed(requested,reduced,explicitlyEnabled),requested&&(!reduced||explicitlyEnabled))
}
equal(network({selected:'trade:40'}).match(/viewBox="([^"]+)"/)[1],network({}).match(/viewBox="([^"]+)"/)[1])
const component = readFileSync('src/SystemActivity.tsx','utf8')
check(!component.includes('localStorage')&&!component.includes('ai_trader_visual_follow'))
check(!/method:\s*['"](?:POST|PUT|DELETE)/.test(component))
check(component.includes('controller.abort()') && component.includes('inFlight') && component.includes("visibilityState === 'hidden'"))
const focus=(item,props={})=>renderToStaticMarkup(createElement(StockFocus,{item,he:true,stale:false,onClose:()=>{},onDetails:()=>{},...props}))
const focusHtml=focus(stock('HOTL'))
check(focusHtml.includes('תקציר המניה במיקוד')&&focusHtml.includes('פתח ראיות מלאות')&&focusHtml.includes('בטל מיקוד'))
check(focusHtml.includes('100.00')&&focusHtml.includes('97.00')&&focusHtml.includes('106.00')&&focusHtml.includes('2.00R'))
check(!focusHtml.includes('TP1')&&!focusHtml.includes('TP3')&&!focusHtml.includes('$'))
check(focus(stock('ECHO')).includes('סיגנל כשיר; הקצאת הדמה חסומה'))
check(focus(stock('GOLF')).includes('אי־ודאות בהתאוששות'))
check(focus(stock('FOXT')).includes('ממתין')&&!focus(stock('FOXT')).includes('כניסה בפועל'))
check(focus(stock('ALFA')).includes('—')&&!focus(stock('ALFA')).includes('0.00R'))
check(focus(stock('ALFA'),{stale:true}).includes('מידע שמור'))
check(focus(stock('HOTL'),{he:false}).includes('Focused stock summary'))
check(focus({...stock('ALFA'),company:'<script>bad</script>',reason:'<img>'}).includes('&lt;script&gt;'))
equal(activityLevels(stock('HOTL')).activeTarget,106)
equal(STATE_SYMBOLS.closed,'■');equal(STATE_SYMBOLS.uncertain,'?')
check(html.includes('system-quick-filters')&&html.includes('system-support-details')&&html.includes('system-full-journey'))
check(!/<details class="system-full-journey"[^>]*\sopen/.test(html)) // selection alone does not unfold/scroll full evidence
check(!network({selected:'trade:40'}).includes('מפה מלאה'))
check(network({}).includes('system-state-key'))
check(component.includes('}, [detailsOpen])')&&!component.includes('}, [selected])\n  const filtered'))
check(css.includes('height: 520px')&&!css.includes('position: fixed'))
// Fixed 2D only; stock details remain reachable in a disclosure, no alternate view.
const plain=render({})
check(plain.includes('system-station-flow')&&plain.includes('system-network-panel')&&!plain.includes('<canvas'))
check(!plain.includes('מפת תלת־ממד')&&!plain.includes('system-view-switch')&&plain.includes('לחצו על מניה לפרטים'))
check(plain.includes('הקצאת דמה חסומה')&&plain.includes('תיעוד בלבד'))
check(plain.includes('תחנות קודמות אינן בהכרח אישור מעבר'))
check(plain.includes('מיקום מתועד, לא מעבר מאומת'))
check(plain.includes('system-flow-name'))
check(!/<details class="system-sample-warning scanner-warning"[^>]*\sopen/.test(plain))
check(plain.includes('מדגם מוגבל — לא כל ההיסטוריה מוצגת'))
check(plain.includes('אין להסיק שאין פעילות במניה שלא מופיעה'))
check(plain.includes('לחיצות וחיפוש אינם משנים מעקב או מסחר'))
check(css.includes('.system-flow-station:not(.is-expanded) .system-flow-name > small { display: none; }'))
check(css.includes('.system-flow-preview { display: grid; grid-template-columns: minmax(0,1fr);'))
check(css.includes('.system-flow-chip span { font-size: 14px;'))
check(css.includes('.system-focus-reason { font-size: 15px; line-height: 1.75;'))
equal((plain.match(/class="system-flow-station /g)||[]).length,8)
equal((plain.match(/class="system-flow-chip /g)||[]).length,9)
check(html.includes('system-flow-focus') && html.includes('system-map-workspace has-selection'))
check(plain.includes('אין רשומות במדגם') === false) // all eight fixture stations populated
const flow=(props={})=>renderToStaticMarkup(createElement(StationFlow,{he:true,items,station:'all',selected:null,select:()=>{},changed:new Set(),stale:false,onDetails:()=>{},...props}))
check(flow({items:[]}).includes('אין רשומות במדגם'))
equal((flow({station:'order'}).match(/class="system-flow-station /g)||[]).length,1)
check(!flow({station:'order'}).includes('HOTL'))
check(flow({selected:'signal:1'}).includes('סיגנל כשיר; הקצאת הדמה חסומה'))
equal((flow({selected:'signal:1'}).match(/סיגנל כשיר; הקצאת הדמה חסומה/g)||[]).length,1)
check(flow({selected:'signal:1'}).includes('פרטים פתוחים — לחצו לסגירה'))
check(flow({selected:'signal:3'}).includes('אי־ודאות בהתאוששות'))
check(flow({he:false}).includes('Waiting for entry or resolution'))
check(flow({changed:new Set(['trade:40'])}).includes('system-arrival'))
const manyRows=Array.from({length:100},(_,n)=>({...stock('HOTL'),id:`row:${n}`,ticker:`ROW${n}`}))
const capped=flow({items:manyRows,selected:'row:99'})
equal((capped.match(/class="system-flow-record"/g)||[]).length,9)
check(capped.includes('ROW99')&&capped.includes('הצג את כל 100 הרשומות'))
check(css.includes('.system-flow-records[hidden] { display: none; }'))
for(const generated_at of [null,'invalid','2099-01-01T00:00:00Z']) {
  const unavailable=render({research:{...research,generated_at},changed:new Set(['trade:40'])})
  check(unavailable.includes('זמן התמונה לא תקין')&&!unavailable.includes('system-arrival'))
}
check(!render({error:'HTTP 503',changed:new Set(['trade:40'])}).includes('system-arrival'))
console.log(`System activity model + RTL rendering: ${assertions} assertions passed`)
