"""Read-only cloud smoke check. No credentials, trading writes, or test signals."""
import json
import os
from datetime import datetime, timezone
from urllib.request import urlopen


def main():
    base=os.environ['BACKEND_URL'].rstrip('/')
    if not base.startswith('https://'): raise ValueError('HTTPS required')
    def get(path):
        with urlopen(base+path,timeout=40) as response:
            assert response.status==200
            return json.load(response)
    get('/health')
    data=get('/api/scanner/dashboard')
    assert data['paper_only'] is True
    assert data['lifecycle_verification']['accounting_ok'] is True
    services={r['component']:r for r in data['services']}
    monitor=services['monitor']
    now=datetime.now(timezone.utc)
    def age(value):
        return (now-datetime.fromisoformat(value.replace('Z','+00:00'))).total_seconds()
    assert monitor['last_success_at'] and age(monitor['last_success_at']) < 900, 'monitor_stale'
    assert monitor['status']!='error', 'monitor_error'
    if not data['market']['is_open']:
        print(json.dumps({'cloud_health':'PASS','live_market':'NOT_VERIFIED_MARKET_CLOSED'}))
        return
    quotes=get('/api/scanner/quotes')
    open_trades=[t for t in data['trades'] if t['status']=='open']
    needed={t['ticker'] for t in open_trades}
    fresh={q['ticker'] for q in quotes['quotes'] if not q['stale']}
    assert needed <= fresh, 'missing_or_stale_quotes:'+','.join(sorted(needed-fresh))
    stale=[t['ticker'] for t in open_trades if not t.get('last_bar_at') or age(t['last_bar_at'])>900]
    assert not stale, 'monitor_cursor_not_progressing:'+','.join(sorted(set(stale)))
    print(json.dumps({'cloud_health':'PASS','fresh_quotes':'PASS','monitor_progress':'PASS',
        'accounting':'PASS','signal_lifecycle_evidence':data['lifecycle_verification']['stages'],
        'live_tp_sl_complete':data['lifecycle_verification']['live_e2e_complete'],
        'note':'No fill is generated by this check. Live TP/SL requires naturally occurring events.'}))


if __name__=='__main__': main()
